version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

  server:
    build: .
    container_name: server
    command: python server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
