version: '3.9'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'

  server:
    build: .
    container_name: server
    image: app:django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  celery:
    restart: always
    build: .
    container_name: celery
    command: celery -A app worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - server
      - redis

  celery-beat:
    build: .
    command: celery -A app beat -l INFO
    depends_on:
      - redis

  redis:
    image: redis:7
